### ISSUE TITLE
list.SetDefaultColumnValues issue with a Document Library

### ISSUE THREAD

**Issue by pmatthews05** [OfficeDev/PnP#548] opened 2015-03-19 09:23 UTC
I'm having an issue with getting the OfficeDevpnp code of SetDefautlColumnValue to work. As far as I can tell, everything is in the correct place after running the code, however when I upload a new file to the document library, when the edit dialog appears, the managed metadata column that is suppose to have the default value in, is not showing. However, if I refresh the dialog, or click cancel the item then has the default value in the managed metadata column. It is as if the 'added' event receiver that suppose to insert the default item in the column fires a little slow and the edit dialog appears before the event receiver has completed. (Sometime the default value does show, but very rarely).

If I do exactly the same as the code manually to a document library, then there doesn't seem to be an issue. I have been speaking to Erwin van Hunen on Yammer at this post about it https://www.yammer.com/itpronetwork/#/Threads/show?threadId=511934252. 

I will include a test code later today.

**Comment by pmatthews05** [comment] 2015-03-20 17:03
A bit late, but I include the code below that I can use to deploy anywhere. You can also remove everything by commenting Create and un commenting delete.

using Microsoft.SharePoint.Client;
using Microsoft.SharePoint.Client.Taxonomy;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security;
using System.Text;
using System.Threading.Tasks;
using OfficeDevPnP.Core.Entities;

namespace SetDefaultColumnValuesDemo
{
    class Program
    {
        //For you to fill in
        static string SHAREPOINTSITE = "";
        static string SPUSER = "";
        static string SPPASSWORD = "";
       
        static Guid GROUPID = new Guid("DC5FCE54-96D9-42EE-A916-2343D9935727");
        static Guid TERMSETID = new Guid("8484FA49-B7E7-4098-BBE6-ED94D801E68F");
        static Guid SITECOLUMNID = new Guid("8C390EBA-D9AD-4C9F-B755-38E515DBF78A");
        static string SITECOLUMNINTERNALNAME = "officedev_TestSiteColumn";
        static string CONTENTTYPEID = "0x01010098E1624BBDB04A409CF65E815E297247";

        static void Main(string[] args)
        {
            ClientContext CC = new ClientContext(SHAREPOINTSITE);
            CC.AuthenticationMode = ClientAuthenticationMode.Default;
            CC.Credentials = new SharePointOnlineCredentials(SPUSER, GetSecureStringPassword(SPPASSWORD));

            Web rootWeb = CC.Web;
            CC.Load(rootWeb);
            CC.ExecuteQueryRetry();

            Create(CC, rootWeb);
            //Delete(CC, rootWeb);

           

            

        }

        private static void Create(ClientContext CC, Web rootWeb)
        {
            //Create required Taxonomy
            CreateTaxonomyGroupAndTerms(CC);
            //Create Site Column
            CreateSiteColumn(CC, rootWeb);
            //Create Content Type
            CreateContentType(CC, rootWeb);
            //Create Document Library
            CreateDocumentLibrary(CC, rootWeb);
            //Create Folders And Set Default Values
            CreateFolderSetDefaultValues(CC, rootWeb);
        }

        private static void Delete(ClientContext CC, Web rootWeb)
        {
            //Delete all.
            DeleteAll(CC, rootWeb);
        }

        private static SecureString GetSecureStringPassword(string password)
        {
            SecureString sStrPwd = new SecureString();

            foreach (char c in password)
            {
                sStrPwd.AppendChar(c);
            }
            return sStrPwd;
        } 

        static void CreateTaxonomyGroupAndTerms(ClientContext CC)
        {
            
            Guid term1ID = new Guid("82824824-6BD3-4989-A9FA-548A2824F45A");
            Guid term2ID = new Guid("8904C49B-E314-496B-B708-23D74B705B17");
            Guid term3ID = new Guid("D7D558B0-6BC5-430F-B79C-7B19B6253FD2");
            Guid term4ID = new Guid("B8F344DF-17B0-4907-84B1-A27660FDE9E8");

            var taxSession = TaxonomySession.GetTaxonomySession(CC);
            var termStore = taxSession.GetDefaultKeywordsTermStore();

            var group = termStore.GetGroup(GROUPID);
            CC.Load(group);
            CC.ExecuteQueryRetry();

            //Create Group
            if((group.ServerObjectIsNull).Value)
            {
                Console.WriteLine("Creating Group");
                group = termStore.CreateGroup("DefaultColumnsGroup", GROUPID);
                CC.Load(group);
                CC.ExecuteQueryRetry();
            }

            //Delete termsets in groups.
            var termSets = group.TermSets;
            CC.Load(termSets);
            CC.ExecuteQueryRetry();

            foreach(var termSet in termSets)
            {
                termSet.DeleteObject();
            }
            CC.ExecuteQueryRetry();


            //Create TermSet
            Console.WriteLine("Creating TermSet");
            var termset = group.CreateTermSet("DefaultColumnTS", TERMSETID, 1033);
            CC.Load(termset);
            CC.ExecuteQueryRetry();
            
            //Create Terms.
            Console.WriteLine("Creating 4 terms");
            termset.CreateTerm("DCTerm1", 1033, term1ID);
            termset.CreateTerm("DCTerm2", 1033, term2ID);
            termset.CreateTerm("DCTerm3", 1033, term3ID);
            termset.CreateTerm("DCTerm4", 1033, term4ID);
            CC.ExecuteQueryRetry();
            
        }

        private static void CreateSiteColumn(ClientContext CC, Web rootWeb)
        {
           if(!rootWeb.FieldExistsById(SITECOLUMNID))
           {
               TaxonomySession session = TaxonomySession.GetTaxonomySession(CC);
               var defaultcolumnTS = session.GetDefaultKeywordsTermStore().GetTermSet(TERMSETID);
               CC.Load(defaultcolumnTS);
               CC.ExecuteQueryRetry();

               Console.WriteLine("Creating Site Column");
               var sitecolumn = new TaxonomyFieldCreationInformation() { Id = SITECOLUMNID, DisplayName = "Test Site Column", Group = "Office Dev", InternalName = SITECOLUMNINTERNALNAME, Required = false };
               sitecolumn.TaxonomyItem = defaultcolumnTS;
               rootWeb.CreateTaxonomyField(sitecolumn);
               CC.ExecuteQueryRetry();

           }
        }

        private static void CreateContentType(ClientContext CC, Web rootWeb)
        {
            if(!rootWeb.ContentTypeExistsById(CONTENTTYPEID, true))
            {
                //Create Content Type
                Console.WriteLine("Creating Content Type");
                rootWeb.CreateContentType("OfficeDevpnp Document", CONTENTTYPEID, "OfficeDevpnp");
                CC.ExecuteQueryRetry();
            }
            

            //add column to content type. won't add if already there.
            Console.WriteLine("Adding Site Column to Content Type");
            rootWeb.AddFieldToContentTypeById(CONTENTTYPEID, SITECOLUMNID.ToString(), false, false);

        }

        private static void CreateDocumentLibrary(ClientContext CC, Web rootWeb)
        {
            List officedevpnpList = null;

            if (!rootWeb.ListExists("Office Dev PNP test"))
            {
                Console.WriteLine("Creating Document Library");
                officedevpnpList = rootWeb.CreateList(ListTemplateType.DocumentLibrary, "Office Dev PNP test", false, true, "OfficeDev", true);
            }
            else
            {
                Console.Write("Loading Document Library");
                officedevpnpList = rootWeb.Lists.GetByTitle("Office Dev PNP test");
            }

            //Double checking incase loading existing list
            
            officedevpnpList.UpdateListVersioning(true, true, false);
            officedevpnpList.ContentTypesEnabled = true;
            officedevpnpList.EnableModeration = true;
            officedevpnpList.EnableFolderCreation = true;
            officedevpnpList.Update();
            CC.ExecuteQueryRetry();

            var documentCT = officedevpnpList.GetContentTypeByName("Document");
            if(documentCT != null)
            {
                Console.WriteLine("Deleting Document Content Type");
                documentCT.DeleteObject();
                officedevpnpList.Update();
            }

            Console.WriteLine("Adding Content Type to List");
            officedevpnpList.AddContentTypeToList(rootWeb.GetContentTypeById(CONTENTTYPEID, true), true);


        }

        private static void CreateFolderSetDefaultValues(ClientContext CC, Web rootWeb)
        {
            var officedevpnpList = rootWeb.Lists.GetByTitle("Office Dev PNP test");

            TaxonomySession session = TaxonomySession.GetTaxonomySession(CC);
            var termSet = session.GetDefaultKeywordsTermStore().GetTermSet(TERMSETID);
            CC.Load(termSet);
            CC.Load(termSet.Terms);
            CC.ExecuteQueryRetry();

            List<IDefaultColumnValue> defaultValues = new List<IDefaultColumnValue>();

            //Loop through terms adding folders
            Console.WriteLine("Checking and Adding Folder items");
            foreach(var term in termSet.Terms)
            {
                var safeFileNameTerm = StripOutBadChar(term.Name.Trim());

                if(!officedevpnpList.RootFolder.FolderExists(safeFileNameTerm))
                {
                    ListItemCreationInformation itemCreateInfo = new ListItemCreationInformation();
                    itemCreateInfo.UnderlyingObjectType = FileSystemObjectType.Folder;
                    itemCreateInfo.LeafName = safeFileNameTerm;

                    ListItem newItem = officedevpnpList.AddItem(itemCreateInfo);
                    newItem["Title"] = safeFileNameTerm;
                    newItem.Update();
                    newItem["_ModerationStatus"] = "0";
                    newItem.Update();
                    CC.ExecuteQueryRetry();
                }

                //Add value to default with folder.
                var defaultColumnValue = new DefaultColumnTermValue();
                defaultColumnValue.FieldInternalName = SITECOLUMNINTERNALNAME;
                defaultColumnValue.FolderRelativePath = safeFileNameTerm;
                defaultColumnValue.Terms.Add(term);
                defaultValues.Add(defaultColumnValue);
            }

            //Not sure if needed, but updating list and execute query.
            officedevpnpList.Update();
            CC.ExecuteQueryRetry();

            //Set Default Column Values.
            Console.WriteLine("Adding Default Column Values");
            officedevpnpList.SetDefaultColumnValues(defaultValues);

        }

        private static string StripOutBadChar(string rawFileName)
        {
            string fileName = rawFileName;
            //special charcters not allowed in filename
            string specialChars = @"\/:*?""<>|#%&.{}~";

            Array.ForEach(specialChars.ToCharArray(), specialChar => fileName = fileName.Replace(specialChar, ' '));
            return fileName;
        }


        private static void DeleteAll(ClientContext CC, Web rootWeb)
        {
            //Delete list.
            List officedevpnpList = null;
            if (rootWeb.ListExists("Office Dev PNP test"))
            {
                Console.WriteLine("Deleting List");
                officedevpnpList = rootWeb.Lists.GetByTitle("Office Dev PNP test");
                officedevpnpList.DeleteObject();
                CC.ExecuteQueryRetry();
            }

            //Delete Content Type.
            if (rootWeb.ContentTypeExistsById(CONTENTTYPEID, true))
            {
                Console.WriteLine("Deleting Content Type");
                var ct = rootWeb.GetContentTypeById(CONTENTTYPEID, true);
                ct.DeleteObject();
                CC.ExecuteQueryRetry();
            }

            //Delete site Column
            if(rootWeb.FieldExistsById(SITECOLUMNID))
            {
                Console.WriteLine("Deleting Column");
                var field = rootWeb.GetFieldById<TaxonomyField>(SITECOLUMNID);
                field.DeleteObject();
                CC.ExecuteQueryRetry();
            }

            //Delete Taxonomy
            Console.WriteLine("Deleting Taxonomy");
            var taxSession = TaxonomySession.GetTaxonomySession(CC);
            var termStore = taxSession.GetDefaultKeywordsTermStore();

            var group = termStore.GetGroup(GROUPID);
            CC.Load(group);
            CC.ExecuteQueryRetry();

            //delete Group
            if (!(group.ServerObjectIsNull).Value)
            {
                //Delete termsets in groups.
                var termSets = group.TermSets;
                CC.Load(termSets);
                CC.ExecuteQueryRetry();

                foreach (var termSet in termSets)
                {
                    termSet.DeleteObject();
                }
                group.DeleteObject();
                CC.ExecuteQueryRetry();   
            }
       }
    }
}

**Comment by nfplay** [comment] 2015-04-16 16:59
I don't think "SetDefaultColumnValuesImplementation" is correct, i'm getting repeated <a href>'s in client_LocationBasedDefaults.html.

Current code is like this:

while (values.Any())
{
   (...)

	var xATag = new XElement("a", new XAttribute("href", path));

	foreach (var defaultColumnValueInSamePath in defaultColumnValuesInSamePath)
	{
		{...}
		xMetadataDefaults.Add(xATag);
		values.Remove(defaultColumnValueInSamePath);
	}
}

I think it should be like this (xATag must be added to xMetadataDefaults only at the end):

while (values.Any())
{
   (...)

	var xATag = new XElement("a", new XAttribute("href", path));

	foreach (var defaultColumnValueInSamePath in defaultColumnValuesInSamePath)
	{
		{...}
		values.Remove(defaultColumnValueInSamePath);
	}
	
	if(xATag.HasElements)
	xMetadataDefaults.Add(xATag);
}

This doesn't fix the problem, but i think it's not correct as it is. What do you think?

**Comment by erwinvanhunen** [comment] 2015-04-16 21:20
Hi Guys,

As I'm the author of this code/functionality, I'll spend some time this weekend to double check and triple check for the issues you're describing. We're unfortunately with limited resources and we've been focusing full force on the provisioning engine right now.

**Comment by nfplay** [comment] 2015-04-17 09:51
Hi Erwin, thanks a lot for your help.

I think the problem is related to the fact that the synchronization of ItemAdded events is Asynchronous by default. In this case, when an item is added we want it to be Synchronous to force the update of current item Before the dialog with the properties is shown.

 So, in this line:

 eventCi.Synchronization = EventReceiverSynchronization.DefaultSynchronization;

 I changed it to:

 eventCi.Synchronization = EventReceiverSynchronization.Synchronous;

 And the problem went away. I can see Paul tried this alternative too, and later it didn't work everytime is this correct? Here, after this correction and the above post code correction regarding repeated "a hrefs", it started working. 
 I can confirm that the manual process of adding default metadata columns adds the same event receiver with synchronization marked as "Synchronous", not "Asynchronous", the default synchronization as it is in the actual code.

**Comment by patrick-rodgers** [comment] 2016-02-05 18:29
Cleaning up due to age. Believe this to be fixed in latest, please let us know if this is still an issue. Thanks!

**Closed by patrick-rodgers** 2016-02-05 18:29 UTC
Labels: Investigation needed
