### ISSUE TITLE
Tests are coupled to bertonline

### ISSUE THREAD

**Issue by pbjorklund** [OfficeDev/PnP#664] opened 2015-04-15 08:10 UTC
The mighty @jansenbe is in lots of places. This is a good thing.
His tenant is also in a lot of places. This is a bad thing.

https://github.com/OfficeDev/PnP/search?p=3&q=%22bertonline.sharepoint.com%22&type=Code&utf8=%E2%9C%93

Did not see an issue reported on this. It hurts to see red tests in my visual studio..

**Comment by VesaJuvonen** [comment] 2015-09-11 17:20
Fixed in later releases. Mistake due limited resources, but got fixed in the May/June release. Thx for reporting as well, since good reminder to get things moving and confirmed.

**Closed by VesaJuvonen** 2015-09-11 17:20 UTC
