### ISSUE TITLE
Can't remove content type from list with the Remove-SPOContentTypeFromList PowerShell cmdlet

### ISSUE THREAD

**Issue by Laskewitz** [OfficeDev/PnP#1069] opened 2015-07-23 12:17 UTC
In my script I'm trying to remove a content type from a list, but it doesn't work. Look at the screenshots below for more info.

This is (a part of) my script:
![ct-item](https://cloud.githubusercontent.com/assets/3766843/8850120/87ee71b0-3145-11e5-978a-4cc4f613f999.png)

The content type still shows after running the script:
![ct](https://cloud.githubusercontent.com/assets/3766843/8850132/a7cf815e-3145-11e5-8399-e0f35bac4075.png)

Off-topic: I use the -DefaultContentType parameter to make all the content types visible at the button New. Is there a more elegant way to to this?

**Comment by erwinvanhunen** [comment] 2015-07-29 22:50
I'm not able to reproduce this issue. Notice that I use Add-SPOContentTypeToList without the -DefaultContentType parameter.

Regarding your other question: when I add a CT to a list it by default shows on the new Button. As long as I don't use the -DefaultContentType parameter. The moment I start to use that one things start indeed start to behave a bit strange. I'll dive into that.

**Comment by erwinvanhunen** [comment] 2015-07-29 22:57
This works for me:
```powershell
New-SPOList -Title $listtitle -Url $listurl -Template GenericList -EnableContentTypes
Add-SPOContentTypeToList -List $listtitle -ContentType "CT 1"
Add-SPOContentTypeToList -List $listtitle -ContentType "CT 2"
Remove-SPOContentTypeFromList -List $listtitle -ContentType "Item"
Set-SPODefaultContentTypeToList -List $listtitle -ContentType "CT 2"
```

 It's not a solution as such, as using the DefaultContentType parameter should have a similar effect.

**Comment by peterstilgoe** [comment] 2015-08-27 15:56
Hi,

Did anyone get this issue resolved, we are experiencing the same, adding etc is fine but remove doesn't error but doesn't actually do anything.

add-SPOContentTypeToList -List "Secure Documents" -ContentType "Team site document" -DefaultContentType (WORKS AS EXPECTED)

Remove-SPOContentTypeFromList -List "Secure Documents" -ContentType "Document" (DOESNT DO ANYTHING)


Cheers

**Comment by erwinvanhunen** [comment] 2015-08-27 15:58
In order to remove a content type that has been marked as default you will have to set another content type as default first with 

```powershell
Set-SPODefaultcontentTypeToList
```

I realize the behaviour is a bit misguiding, and I'll come up with at least some error message instead if someone tries to delete the default content type

**Comment by peterstilgoe** [comment] 2015-08-27 16:07
Hi

They are run in the order above so it goes:

- Start with a new clean site with OOTB DocLIb so 'Document' is default CT.

- Run add-SPOContentTypeToList -List "Secure Documents" -ContentType "Team site document" -DefaultContentType "

- So now the DocLIb has a new content type called "Team site document" which is set as the default & have the OOTB 'Document' CT which is no longer default

All works as expected here.

- Now run Remove-SPOContentTypeFromList -List "Secure Documents" -ContentType "Document" to try & delete 'Document' which is not the default CT and nothing happens.

Have tried various variations etc but no matter what don't seem the be able to remove the OOTB 'document' CT

Cheers

**Comment by peterstilgoe** [comment] 2015-09-02 10:32
Hi

Done some more testing & it seems it will work on a newly created document library but not on the OOTB 'Documents' library eg.

Create new document library:

New-SPOList -Title "Documents2" -Template DocumentLibrary -QuickLaunchOptions off ##WORKS##

Add-SPOContentTypeToList -List "Documents2" -ContentType "Team site document" -DefaultContentType ##WORKS##

Remove-SPOContentTypeFromList -List "Documents2" -ContentType "Document" ##WORKS##


Using the OOTB 'Documents' library:

Add-SPOContentTypeToList -List "Documents" -ContentType "Team site document" -DefaultContentType ##WORKS##

Remove-SPOContentTypeFromList -List "Documents" -ContentType "Document" ##DOES NOTHING BOTH CONTENT TYPES REMAIN##



Cheers

**Comment by peterstilgoe** [comment] 2015-09-03 16:10
Further testing update - I can only get this to work from the Root site, it works fine from the Root site, but when run against a sub site it doesn't do anything, can anyone else reproduce this ?  I am using O365 BTW.

Cheers

**Comment by arangas** [comment] 2016-03-23 04:52
I just tried this in Office 365 using both a root site and sub-site, specifically the out-of-the-box Documents library. I wasn't able to reproduce any issues removing the content types as described by @peterstilgoe .

**Comment by VesaJuvonen** [comment] 2016-05-12 16:05
thx Alex for the assistance around validation. If this is still an issue, we'd ask this to be reported in the PnP Core Component repository at https://github.com/OfficeDev/PnP-sites-core. PowerShell ultimately calls core component.

**Closed by VesaJuvonen** 2016-05-12 16:05 UTC
Labels: Investigation needed, Port to PnP-PowerShell
