### ISSUE TITLE
Cant Provision Composed Looks logo file when logo is in /rootsite/subsite/siteassets_doclib/logo.jpg 

### ISSUE THREAD

**Issue by ScoutmanPt** [OfficeDev/PnP#1049] opened 2015-07-16 16:24 UTC
Hi guys, im trying to provisioning the logo locally (FileSystemConnector) to apply it later on.
The logo is in https://corp.sharepoint.com/clients/cli/SiteAssets document library but somewhere in the way the path get confused...

Here's the msg "File logo.jpg not found in site https://corp.sharepoint.com/clients/cli, library https://corp.sharepoint.com/SiteAssets ".

Deep diging i notice in the OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectComposedLook  line 238
" // Strip the /sites/root part from /sites/root/lib/folder structure
            Uri u = new Uri(webUrl);
            if (f.Folder.IndexOf(u.PathAndQuery, StringComparison.InvariantCultureIgnoreCase) > -1)
            {
                f.Folder = f.Folder.Replace(u.PathAndQuery, "");
            }
"
, that broke the path. 
Seems to me that if we want to provisioning template within susbsites this code doesnt work.

**Comment by ScoutmanPt** [comment] 2015-07-16 17:36
Just tested the Composed look in a root site, with a logo and background page and it is also broken.

**Comment by karlsquell** [comment] 2015-07-27 13:48
Can confirm I do have the same problem.

**Comment by VesaJuvonen** [comment] 2016-01-20 15:39
Sorry for the delayed response on this. We did significant re-structure of the logo and compose looks handling in the latest releases of the engine. Logo handling has been relocated to site level handler, which takes pretty much any value and uses that for the logo URL. This is done, so that you can easily pin-point also logo files which could be located outside of SharePoint. We could not reproduce above issue anymore, so closing issue.

**Closed by VesaJuvonen** 2016-01-20 15:39 UTC
