### ISSUE TITLE
Publishing Fields and Content Types are added to the Provisioning Template

### ISSUE THREAD

**Issue by strategik** [OfficeDev/PnP#1165] opened 2015-09-10 01:00 UTC
If a user creates a team site and then activates the publishing infrastructure, additional site columns and content types are added to the site (Reusable HTML, Page Output Cache etc.). When a provisioning template is generated from the site, these columns and content types are added to the template (as well as the requirement for the feature dependency). However, these columns should not be provisioned in the target site, which should instead have the same publishing features activated?  Is this expected behaviour or something that we need to fix up?

**Comment by VesaJuvonen** [comment] 2015-09-14 06:10
This is actually by design. When we retract the template, we extract any customization compared to oob underlying template. Since in this case, template is oob team site, also the settings introduced by the publishing features will be included.

In practice this is more inconvenience, since we always activate first all features in the target site and then check if the existing CTs or lists already exists when we move to those sections. This means that even though they exists in the template, they will be ignored, since they were already created when feature was activated.

In general we (engineering) do not recommend activation of the publishing features on top of team sites, rather usage of publishing sites then based on the business scenario. This does however happen quite often, which indeed can cause pretty big template definitions, but that impacts only on the provisioning time needed for the new sites and should not have any other impact.

This is actually pretty similar use case when you'd do "Save site as a template" for oob team site where the publishing features are enabled. That will result pretty ugly onet.xml and massive amount of xml definitions in the wsp package.

I'll close this for now as it was pretty much "as designed". If there's however any complications caused by this approach, please let us know and re-open the issue. 

Thx for reporting this.

**Closed by VesaJuvonen** 2015-09-14 06:10 UTC
