### ISSUE TITLE
Bug in Set Property Bag on a list.

### ISSUE THREAD

**Issue by pmatthews05** [OfficeDev/PnP#423] opened 2015-02-04 09:33 UTC
While working with OfficeDEVpnp in my project I have noticed a bug in the  ListExtensions class. The method SetPropertyBagValueInternal. Just before list.Context.ExecuteQuery() it calls list.Update(). This should be list.RootFolder.Update();

**Comment by ronnieholm** [comment] 2015-02-07 23:23
@pmatthews05 Could you elaborate on why the existing code is buggy? What goes wrong with the existing code?

**Comment by pmatthews05** [comment] 2015-02-08 04:55
Sure, I had to update 2 properties at once. These were new properties so it actually created them.  The first time I called the method it seems to work, which could be the reason why no one has noticed the bug. However, if you call the method a second time, the error message complains that it can't find the first property I added. By performing an update on the RootFolder instead of the list fixes this issue.

**Comment by ronnieholm** [comment] 2015-02-08 16:16
I can't reproduce the described behavior. 

@pmatthews05: can you provide a failing test case?

Here's my passing one: 

        [TestMethod()]
        public void SetPropertyBagValueTest()
        {
            using (var clientContext = TestCommon.CreateClientContext())
            {
                var listName = "Test_list_" + DateTime.Now.ToFileTime();

                //Create List
                var web = clientContext.Web;
                web.CreateList(ListTemplateType.GenericList, listName, false);

                //Get List
                var list = web.GetListByTitle(listName);

                //Set property bag values
                list.SetPropertyBagValue("key1", "value1");
                list.SetPropertyBagValue("key2", "value2");

                var value1 = list.GetPropertyBagValueString("key1", "default");
                var value2 = list.GetPropertyBagValueString("key2", "default");
                //var value3 = list.GetPropertyBagValueString("dontExist", "default");

                Assert.AreEqual("value1", value1);
                Assert.AreEqual("value2", value2);
                //Assert.AreEqual("value3", "default");   // <- failure. Default value not used

                //Delete List
                list.DeleteObject();
                clientContext.ExecuteQueryRetry();
            }
        }

The default value passed to GetPropertyBagValueString is never used. Hence, the commented out assertion fails (that's another bug).

**Comment by pmatthews05** [comment] 2015-02-08 18:30
@ronnieholm just looking quickly at your test, the difference I see between your test and my code is that I'm checking if property exists before setting it. It is here where the error message pops up, however it's the setpropertybagvalue that needs the root.update to fix the issue. I don't have my code at hand, and won't be viewing it until tomorrow. I can paste it here tomorrow, unless this is enough information for you.

**Comment by ronnieholm** [comment] 2015-02-08 18:37
The above test case does all its work within a single client context. Sometimes this would hide a bug because the same state isn't present in a future client context.

I tested with SetPropertyBagValue in one client context and reading the values in another. It works in my case.

Better paste in your code tomorrow.

**Comment by pmatthews05** [comment] 2015-02-09 13:07
Hi @ronnieholm , Looks like I need to apologise. I was preparing the test for you today ready to copy the code, and I wasn't able to replicate my error. Which is really annoying because last week, I spent at least 3 hours looking into this with the error appearing, which brought me to the conclusion that the rootfolder needed updating instead of the list.

I've tried it on my existing code, and creating a brand new project just to perform this action, new site collection and library and all pass correctly.

I'm really sorry, and grateful for you spending your time on this.

I've included my code anyway.

        static void Main(string[] args)
        {
            ClientContext CC = new ClientContext("https://dev/sites/DemoSite");
            CC.AuthenticationMode = ClientAuthenticationMode.Default;
            CC.Credentials = new System.Net.NetworkCredential("cf\\Paul", "Password");

            Web rootWeb = CC.Web;
            CC.Load(rootWeb);
            try
            {
                List documentLibrary = rootWeb.Lists.GetByTitle("Documents");
                CC.Load(documentLibrary);
                CC.ExecuteQuery();

                if (!documentLibrary.PropertyBagContainsKey("MyListProperty1"))
                {
                    documentLibrary.SetPropertyBagValue("MyListProperty1", "value1");
                }

                 if (!documentLibrary.PropertyBagContainsKey("MyListProperty2"))
                {
                    documentLibrary.SetPropertyBagValue("MyListProperty2", "value2");
                }
               
                Console.ReadLine();
            }
            catch (Exception ex)
            {
                Console.WriteLine("Error" + ex.Message);
                Console.ReadLine();
            }
        }

**Comment by VesaJuvonen** [comment] 2015-02-11 16:43
Closing based on the conclusion.

**Closed by VesaJuvonen** 2015-02-11 16:43 UTC
Labels: Investigation needed
