### ISSUE TITLE
Contenttype provisioning broken ??

### ISSUE THREAD

**Issue by xtrmdev** [OfficeDev/PnP#1192] opened 2015-10-08 18:45 UTC
In a clean site collection i am now unable to deploy content types ?

I mean basic stuff keeps breaking for every release ? It has been impossible to upgrade the last 2 months. A lot get's fixed, and new basic bugs are introduced..
Very frustrating.

Sept release:
Create contenttype with site fields = Ok.
Add new field to contenttype = crash.
Adding properties to web propertybag in xml = not working.
Need to remove _vti_<css branding prop something> before deploy, else = crash.

Okt release:
In a clean site collection, the contenttype gets created, one field is added then crash.
Rerun = one more field is added to ct, then crash.
Existing contenttype, adding ONE field = ok. 
Existing contenttype, adding TWO fields = one added, then crash.

Adding one field works very well actually, all contenttypes and lists are updated.
But adding a bool site col with default value = true, results in the field beeing false on existing documents/items.

How about implementing some kind of automated tests ? This should really have been caught and never been released.

It's unfortunately two steps forward and one step back with this framework.

Sorry, just beeing frustrated.. :/

**Comment by PieterVeenstra** [comment] 2015-10-08 19:54
I had the same today. I've got the feeling that it is related to my Managed Metadata fields. I'm planning to test this tomorrow. Do you get errors about 'id' not being loaded?

**Comment by xtrmdev** [comment] 2015-10-08 20:06
Yes, i beleive it was fieldlink get_id() something.
Property not initialized. :)

**Comment by PieterVeenstra** [comment] 2015-10-09 09:07
Using the PowerShell commands I'm getting:
Apply-SPOProvisioningTemplate : The property or field 'Id' has not been initialized. It has not been requested or the request has not been executed. It may need to be explicitly requested.

The following line (748) in FieldAndContentTypeExtensions.cs
 var flink = contentType.FieldLinks.FirstOrDefault(fld => fld.Id == field.Id);

is causing the problem. The array of contentType.FieldLinks now contains all the existing fields of the content type and the field that was last added.For this last added field the ID field is not initialised.

So When a field is added the id field should be initialised in this array so that when the next field is added the array can be checked for the existence of the field.

I fixed this by adding the following line :

contentType.FieldLinks[contentType.FieldLinks.Count - 1].EnsureProperties(f => f.Id);
            
I inserted this on line 746 just before the above failing line on line number 746. 

This fixed it for me.

**Comment by VesaJuvonen** [comment] 2015-10-09 09:31
Thanks for submitting these. Obviously we do not want to have any bugs and are doing testing on each release, but not for every use case. It's also important to notice that PnP is community driven program without any full time resources and majority of this work is done by people during evenings and weekends after customer facing work is completed. This is the main reason why we absolutely need input and assistance also from others from community, since the small group currently working on engine has their day job as well.

We are also looking to have automated testing in the PnP engine during future. This is obviously highly dependent on available resources and contributions from the community, like any other element in the PnP. 

On the actual bug: It's good that this thread already contains additional details around the issue and that it seems to be based on the taxonomy fields. For easier troubleshooting and to verify that fix is applied accordingly, we would highly appreciate also reference xml files, so that we can easily reproduce the issue - when it can be reproduced, it can be fixed.

If you prefer not to share that at GitHub, you can also send me the attachment for example using private message at Yammer. Thanks for the xml files advance.

**Comment by VesaJuvonen** [comment] 2015-10-09 09:32
Thank you Pieter for the specific fix already on this one. We'll verify and get that included in the Core component if all is good. Really valuable stuff.

**Comment by PieterVeenstra** [comment] 2015-10-09 09:33
Hi Vesa,

The MMS field may have been a red herring. 

The fix in my last message worked for me and content types are created again.

PS: Great work on this PnP project! I like it a lot and my customer too.

**Comment by VesaJuvonen** [comment] 2015-10-16 13:23
Taxonomy fields have been fixed with the updated Oct release done earlier today. We should be all good for this one. Thx everyone for reporting these issues.

**Closed by VesaJuvonen** 2015-10-16 13:23 UTC
