### ISSUE TITLE
Encoding needs to be removed when setting theme files SetComposedLookByUrl

### ISSUE THREAD

**Issue by tasmanb** [OfficeDev/PnP#1040] opened 2015-07-13 09:35 UTC
I get this error when setting a theme on a site with spaces in the url:
/_catalogs/masterpage/seattle.master" contains invalid character '%'

Method: SetComposedLookByUrl.

I think the relative urls need to be unescaped: "Uri.UnescapeDataString"

**Comment by ms007** [comment] 2015-12-11 12:14
I have noticed that issue too. Should be without encoding

**Comment by patrick-rodgers** [comment] 2016-02-05 19:47
Thanks for finding this - could you provide line number(s) or better describe where you believe the change is needed? Want to make sure we are looking at the right code.

**Comment by arangas** [comment] 2016-03-23 04:40
I've tested this in Office 365 using a site collection with spaces in the URL, as well as a composed look with spaces in the name ("Sea Monster"). I wasn't able to reproduce this issue.

Can you still repro this @tasmanb or @ms007 and if so can you please give more details?

**Comment by VesaJuvonen** [comment] 2016-05-12 11:36
This should have been addressed already like Alex is pointing out. Since there was no additional information available, will close the issue. If this is still an issue in certain scenarios, would suggest to open up a new pull request in the PnP Sites Core repository at https://github.com/OfficeDev/PnP-Sites-Core. thx.

**Closed by VesaJuvonen** 2016-05-12 11:36 UTC
Labels: bug, Investigation needed
