### ISSUE TITLE
Cmdlets: Set-SPOGroup specifying the -Web parameter

### ISSUE THREAD

**Issue by mahajangaurav** [OfficeDev/PnP#1100] opened 2015-08-03 20:11 UTC
While the -Web parameter works fine for New-SPOGroup, so you can specify the web where the group should be created, it does not work for the Set-SPOGroup command and gives an invalid context error

**Comment by erwinvanhunen** [comment] 2015-08-03 20:13
what specific parameters do you use with the cmdlet? It will help me in debugging it.

**Comment by mahajangaurav** [comment] 2015-08-03 20:25
Thanks for the prompt response:
`Connect-SPOnline -Url $RootSiteUrl -CurrentCredentials`
`$SomeWeb = New-SPOWeb -Url "Some" -Title "Some Site" -Template "STS#0" -BreakInheritance:$true -InheritNavigation:$true ``
                                     -Description "This website is used to generate and manage some stuff` `$VisitorsGroup = New-SPOGroup -Title "Some Site Visitors" -Web $SomeWeb -AllowRequestToJoinLeave:$true`
`Set-SPOGroup -Identity $VisitorsGroup -SetAssociatedGroup Visitors -Web $SomeWeb`
The error i get is this:
Set-SPOGroup : The object is used in the context different from the one associated with the object.
At line:1 char:1
+ Set-SPOGroup -Identity $VisitorsGroup -SetAssociatedGroup Visitors -Web $Collate ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Set-SPOGroup], InvalidOperationException
    + FullyQualifiedErrorId : EXCEPTION,OfficeDevPnP.PowerShell.Commands.Principals.SetGroup

**Comment by mahajangaurav** [comment] 2015-08-03 20:27
Sorry, just to be clear, this is on-prem

**Comment by erwinvanhunen** [comment] 2015-08-03 20:48
I can confirm this to be an issue. Until I fixed it I can offer this workaround

```powershell
Connect-SPOnline -Url $RootSiteUrl -CurrentCredentials
$SomeWeb = New-SPOWeb -Url "Some" -Title "Some Site" -Template "STS#0" -BreakInheritance:$true -InheritNavigation:$true -Description "This website is used to generate and manage some stuff"
$VisitorsGroup = New-SPOGroup -Title "Some Site Visitors" -Web $SomeWeb -AllowRequestToJoinLeave:$true
Connect-SPOnline -Url $RootSiteUrl/Some -CurrentCredentials
Set-SPOGroup -Identity $VisitorsGroup.Title -SetAssociatedGroup Visitors
```

The reason this works is because of the added connect-sponline statement and the modified Set-SPOGroup cmdlet. During the context switching behind the scenes there are some mismatches between the context of the group returned and the context used in the Set-SPOGroup statement.

**Comment by mahajangaurav** [comment] 2015-08-03 21:20
Thanks again Erwin! Yes, there are a few other commands that i intend to run on the child web and I intended to use this workaround to circumvent the issue for now! I'll look forward to the fix when you can but its not super critical for me at least :)

**Comment by erwinvanhunen** [comment] 2015-08-04 09:35
I just merged a change into the dev branch: PR #1103. With that update I can run your PS snippet succesfully without requiring the additional connect-sponline. This PR will be merged into the master branch next month.

**Comment by erwinvanhunen** [comment] 2015-08-04 09:35
I will close this issue now.

**Closed by erwinvanhunen** 2015-08-04 09:35 UTC

**Comment by mahajangaurav** [comment] 2015-08-04 14:26
Thanks for the quick turnaround Erwin! Kudos!

**Comment by brannmar** [comment] 2015-09-02 07:25
@erwinvanhunen Does this apply when trying to add a field to a list in a subweb where the field is from the rootweb?
